#! /bin/sh

bspc config border_width        10
bspc config window_gap         	20
bspc config top_padding		60

bspc config split_ratio         0.5
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true
bspc config focus_follows_pointer true

bspc monitor -d home inet term work misc

bspc rule -a Gimp desktop=^8 follow=on floating=on
bspc rule -a Chromium desktop=^2
bspc rule -a mplayer2 floating=on
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a google-chrome-unstable border_width=0

#pkill compton
#pkill panel
#pkill feh
#pkill mpd
#pkill syndaemon
#
#mpd &
#
#panel &
#
#/home/anon/.fehbg
#
#compton &
#
#syndaemon -i 0.5 -d
#
#xset +fp /usr/share/fonts/local
#xset +fp /home/anon/.lokaltog-fonts/
#xset fp rehash
